parameters:
- name: sourceBranch
  type: string
- name: baseDeputyDirectory
  type: string

steps:

- task: PowerShell@2
  name: prepareVariables
  displayName: 'Prepare variables'
  inputs:
    targetType: 'inline'
    script: |
      # Set variables based on the Build.SourceBranch, replacing characters to make it ready for future tasks
      $sourceBranch = "${{ parameters.sourceBranch }}"

      echo "##vso[task.setvariable variable=BaseDeputyDirectory;]${{ parameters.baseDeputyDirectory }}"

      $sourceBranchShort = $sourceBranch.Replace('refs/heads/', '')
      $sanitizedBranchName = $sourceBranchShort -replace "[^a-zA-Z0-9]", "_"
      $deputyBranchDirectory = "${{ parameters.baseDeputyDirectory }}\$sanitizedBranchName";
      $deputyStagingDirectory = "$deputyBranchDirectory\Staging";
      $deputyReleaseDirectory = "$deputyBranchDirectory\Releases";

      Write-Host "Source Branch: $sourceBranch"
      Write-Host "Source Branch Short: $sourceBranchShort"
      Write-Host "Sanitized Branch Name: $sanitizedBranchName"
      Write-Host "Deputy Branch Directory: $deputyBranchDirectory"
      Write-Host "Deputy Staging Directory: $deputyStagingDirectory"
      Write-Host "Deputy Release Directory: $deputyReleaseDirectory"

      echo "##vso[task.setvariable variable=SourceBranchShort;]$sourceBranchShort"
      echo "##vso[task.setvariable variable=SanitizedBranchName;]$sanitizedBranchName"
      echo "##vso[task.setvariable variable=DeputyBranchDirectory;]$deputyBranchDirectory"
      echo "##vso[task.setvariable variable=DeputyStagingDirectory;]$deputyStagingDirectory"
      echo "##vso[task.setvariable variable=DeputyReleaseDirectory;]$deputyReleaseDirectory"
